### ISSUE TITLE
java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest

### ISSUE THREAD

**Issue by zhulongchao** [heroku/predictionio-engine-ur#1]
enviroment: els:5.2.2 spark:2.1.0 scala:2.11.8 pio:0.11.1-SNAPSHOT

pio-data-elasticsearch-assembly-0.11.1-SNAPSHOT.jar has this method

run "pio train " throw exception below

Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequest(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;[Lorg/apache/http/Header;)Lorg/elasticsearch/client/Response;
	at org.template.EsClient$.createIndex(EsClient.scala:134)
	at org.template.EsClient$.hotSwap(EsClient.scala:220)
	at org.template.URModel.save(URModel.scala:80)
	at org.template.URAlgorithm.calcAll(URAlgorithm.scala:323)
	at org.template.URAlgorithm.train(URAlgorithm.scala:250)
	at org.template.URAlgorithm.train(URAlgorithm.scala:166)
	at org.apache.predictionio.controller.P2LAlgorithm.trainBase(P2LAlgorithm.scala:49)
	at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:692)
	at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:692)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.predictionio.controller.Engine$.train(Engine.scala:692)
	at org.apache.predictionio.controller.Engine.train(Engine.scala:177)
	at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
	at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:250)
	at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by mars** [comment]
Hi @zhulongchao ,

This error is happening because Elasticsearch support on Heroku requires a [forked version of PredictionIO](https://github.com/mars/incubator-predictionio/tree/esclient-auth). You are of course welcome to try this, but deploying an alternate version of PIO is quite challenging.

We'll be documenting the setup we have working in this repo soon. Until then, you can get started with [the buildpack's local development](https://github.com/heroku/predictionio-buildpack/blob/master/DEV.md) workflow which includes the special version of PredictionIO to support Elasticsearch.

**Comment by zhulongchao** [comment]
@mars ,thanks
deploy the [ forked version of PredictionIO. ](https://github.com/mars/incubator-predictionio/tree/esclient-auth) ,it is ok now.
when elasticsearch is cluster deployment, should configure the "es.nodes" in the engine.json
